
# # Example config

# version: '3.2'

# services:
#   car-thing-builder:
#     image: bishopdynamics/car-thing-builder:latest
#     container_name: car_thing_builder
#     build: .
services:
  u_boot_imx6:
    build: .
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    user: root
    volumes:
      - .:/src/workspace
      - ./build_output:/tmp/build_output
# volumes:
#   workspace:
#     driver: local
#   build_output: 
#     driver: local
  