name: docker-compose-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

permissions:
    contents: write
    
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      # - run: |
      #     sudo chown -R runner:docker ./

    # sudo chown :1000 testdir/
    # sudo chmod g+s testdir/

      - name: Build the stack
        run: |
          docker compose up --build && docker compose down 
    # ./build.sh
        
#       - name: Archive Release
#         uses: thedoctor0/zip-release@master
#         with:
#           type: 'zip'
#           directory: "workspace/fhir"
#           filename: "${{ env.targetZip }}"

      # - name: Release prebuilt
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "build_output/*.zip"
      #     allowUpdates: true
      #     token: ${{ secrets.GITHUB_TOKEN }}
        
#       - name: Archive Release
#         uses: thedoctor0/zip-release@master
#         with:
#           type: 'zip'
#           directory: "u-boot-imx6/${{ env.installationPath }}"
#           filename: "${{ env.mingwTargetZip }}"
        
#       - name: Release prebuilt
#         uses: ncipollo/release-action@v1
#         with:
#           artifacts: "u-boot-imx6/${{ env.installationPath }}/${{ env.mingwTargetZip }}"
#           allowUpdates: true
#           token: ${{ secrets.GITHUB_TOKEN }}


# cd u-boot-imx6
# export CROSS_COMPILE=aarch64-none-elf-
# # optionally add options to configs/mx6cuboxi_defconfig
# make mx6cuboxi_defconfig
# # optionally configure u-boot graphically
# # make menuconfig
# make

# git clone --branch v2018.01-solidrun-imx6 https://github.com/SolidRun/u-boot.git u-boot-imx6
# cd u-boot-imx6
# export CROSS_COMPILE=<Set toolchain prefix to your toolchain>
# # optionally add options to configs/mx6cuboxi_defconfig
# make mx6cuboxi_defconfig
# # optionally configure u-boot graphically
# # make menuconfig
# make
